### ISSUE TITLE
FindAllInteractionPrograms Error: Error in `$<-.data.frame`(`*tmp*`, "id", value = 1:0) :    replacement has 2 rows, data has 0

### ISSUE THREAD

**Issue by alwhiteh** [BlishLab/scriabin#8]
Hello,

While the vignette using the pancreas data worked fine for me, I'm having some issues using my own Seurat objects. 

Specifically, when I run:

```
lung_IP <- FindAllInteractionPrograms(lung.combined,
                                      group.by = "CellTypes", assay = "alra")
```

I get the following error:

```
Using database OmniPath
Error in `$<-.data.frame`(`*tmp*`, "id", value = 1:0) : 
  replacement has 2 rows, data has 0
```

I tried this with both the 'alra' and 'integrated' assays. Is there some other manipulation of the seurat object that needs to be performed first? 

Best,

Alex

**Comment by ajwilk** [comment]
Hi Alex, 
Agree seems like a dataset-specific problem. Can you send me a full `traceback()`? Also, is this a human dataset? Would be good to check that your gene names match what is pulled in from the database. If we can't find a quick and obvious answer may need to ask you to send me a sample of your dataset to try to reproduce. 
Thanks!

**Comment by alwhiteh** [comment]
Hi Aaron,

The dataset is from mice - I'm guessing that human is the only supported organism?

On the off chance, there's another issue, here's the traceback:

```
rlang::last_trace()
<error/tibble_error_column_names_must_be_unique>
Error in `rownames_to_column()`:
! Column name `cell` must not be duplicated.
Caused by error in `repaired_names()`:
! Names must be unique.
✖ These names are duplicated:
  * "cell" at locations 58 and 68.
---
Backtrace:
    ▆
 1. ├─scriabin::FindAllInteractionPrograms(...)
 2. │ └─base::lapply(...)
 3. │   └─scriabin (local) FUN(X[[i]], ...)
 4. │     └─scriabin::InteractionPrograms(object = x, return.mat = T, ...)
 5. │       └─base::lapply(...)
 6. │         └─scriabin (local) FUN(X[[i]], ...)
 7. │           └─object@meta.data %>% rownames_to_column("cell")
 8. └─tibble::rownames_to_column(., "cell")
 9.   └─tibble:::repaired_names(c(unique(names2(df)), var), repair_hint = FALSE)
```

I checked the cell names by running:

```
test <- colnames(lung.combined) #21977 elements
head(test)

> [1] "SC_AAACCCACAAATCCCA-1" "SC_AAACCCACACCAGTTA-1" "SC_AAACCCACATGGAATA-1" "SC_AAACCCAGTCTCCCTA-1" "SC_AAACCCATCACATCAG-1"
> [6] "SC_AAACCCATCACCTACC-1"

test2 <- unique (test) #21977 elements
```
so I think that my cell names should all be unique?

**Comment by ajwilk** [comment]
Ah, there's the issue! By default Scriabin assumes a human dataset and imports a human ligand-receptor pair database (OmniPath by default). Specify ```species = "mouse"``` and that should fix it. feel free to re-open with other questions

**Comment by alwhiteh** [comment]
Hi @ajwilk,

I set the species to mouse and re-ran the command, but am still getting a similar error:

```
Iteratively generating interaction matrix
Will perform 4 iterations to approximate TOM
Error in `rownames_to_column()`:
! Column name `cell` must not be duplicated.
Caused by error in `repaired_names()`:
! Names must be unique.
✖ These names are duplicated:
  * "cell" at locations 20 and 65.
Run `rlang::last_trace()` to see where the error occurred.
> rlang::last_trace()
<error/tibble_error_column_names_must_be_unique>
Error in `rownames_to_column()`:
! Column name `cell` must not be duplicated.
Caused by error in `repaired_names()`:
! Names must be unique.
✖ These names are duplicated:
  * "cell" at locations 20 and 65.
---
Backtrace:
    ▆
 1. ├─scriabin::FindAllInteractionPrograms(...)
 2. │ └─base::lapply(...)
 3. │   └─scriabin (local) FUN(X[[i]], ...)
 4. │     └─scriabin::InteractionPrograms(object = x, return.mat = T, ...)
 5. │       └─base::lapply(...)
 6. │         └─scriabin (local) FUN(X[[i]], ...)
 7. │           └─object@meta.data %>% rownames_to_column("cell")
 8. └─tibble::rownames_to_column(., "cell")
 9.   └─tibble:::repaired_names(c(unique(names2(df)), var), repair_hint = FALSE)
```

-Alex
